name: codesense_ai
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  firebase_storage: ^11.0.0
  file_picker: ^5.0.0
  firebase_vertexai: ^0.1.0
  firebase_app_check: ^0.2.2+7
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.7
  pdf: ^3.11.3
  printing: ^5.13.1
  introduction_screen: ^3.1.17
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
