// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ0CpSKV0KFO0JHYrL7Ui7JsIZiRgoeUE',
    appId: '1:45960572180:web:e32277f53d2976eb3fa601',
    messagingSenderId: '45960572180',
    projectId: 'codesense-ai-2025',
    authDomain: 'codesense-ai-2025.firebaseapp.com',
    storageBucket: 'codesense-ai-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsSgLB8cup8-4cHwwXs0oKNuDwxar_BdY',
    appId: '1:887600116059:android:340ccbd7415a1046352a7e',
    messagingSenderId: '887600116059',
    projectId: 'codesense-ai-88778',
    storageBucket: 'codesense-ai-88778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxzJLfM4ENmvREQNolVU6GQ3khuKdEnU',
    appId: '1:887600116059:ios:5f0471b85f99bdad352a7e',
    messagingSenderId: '887600116059',
    projectId: 'codesense-ai-88778',
    storageBucket: 'codesense-ai-88778.firebasestorage.app',
    iosBundleId: 'com.example.codesenseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxzJLfM4ENmvREQNolVU6GQ3khuKdEnU',
    appId: '1:887600116059:ios:5f0471b85f99bdad352a7e',
    messagingSenderId: '887600116059',
    projectId: 'codesense-ai-88778',
    storageBucket: 'codesense-ai-88778.firebasestorage.app',
    iosBundleId: 'com.example.codesenseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh5mqBa2z00uJUfWZj3c4Xnfp7NAjnceQ',
    appId: '1:887600116059:web:ba966f42437d2607352a7e',
    messagingSenderId: '887600116059',
    projectId: 'codesense-ai-88778',
    authDomain: 'codesense-ai-88778.firebaseapp.com',
    storageBucket: 'codesense-ai-88778.firebasestorage.app',
    measurementId: 'G-XMTB1G51MC',
  );
}